export const pricing = {
  gstNote: 'All prices are exclusive of GST. Prices shown are per outlet per month.',
  plans: [
    {
      code: 'LITE',
      title: 'Lite',
      priceMonthly: '₹599/mo',
      annual: '₹5,990/yr (save 2 months; billed upfront)',
      trialNote: 'No free trial. Payment required from day one.',
      highlights: ['1 outlet included (+₹599/mo each additional outlet; max 3 outlets)', 'Up to 100 active customers'],
      features: [
        { label: 'Loyalty cards (standard design)', value: '1 (+₹299 per extra card; max 3 total)' },
        { label: 'Custom card design', value: 'Included (free)' },
        { label: 'Special offers module', value: '—' },
        { label: 'Push Notifications', value: '—' },
        { label: 'Campaigns', value: '—' },
        { label: 'Dashboard analytics', value: 'Basic' },
        { label: 'Support SLA', value: '48 hrs (Email + Ticket)' },
      ],
    },
    {
      code: 'GROWTH',
      title: 'Growth',
      badge: 'Most popular',
      priceMonthly: '₹999/mo',
      trialNote: '30-day free trial (no card required to start; payment method by day 21).',
      annual: '₹9,990/yr (save 2 months; billed upfront)',
      highlights: ['1 outlet included (+₹999/mo each additional outlet)', 'Unlimited active customers'],
      features: [
        { label: 'Loyalty cards (standard design)', value: '3 (+₹299 per extra card)' },
        { label: 'Custom card design', value: 'Included (free)' },
        { label: 'Special offers module', value: 'Unlimited' },
        { label: 'Push Notifications', value: 'Unlimited' },
        { label: 'Campaigns', value: '5 / month' },
        { label: 'Dashboard analytics', value: 'Advanced' },
        { label: 'Support SLA', value: '24 hrs (Email + Ticket + Phone)' },
      ],
    },
    {
      code: 'PRO',
      title: 'Pro',
      priceMonthly: 'From ₹2,999/mo',
      annual: 'Custom annual',
      trialNote: 'Demo call (trial terms agreed during onboarding).',
      highlights: ['Custom plan for larger requirements'],
      features: [
        { label: 'Outlets included (base plan)', value: '3 (+₹799/outlet/mo up to 10; 11+ custom)' },
        { label: 'Loyalty cards (standard design)', value: 'Unlimited' },
        { label: 'Custom card design', value: 'Included (free)' },
        { label: 'Campaigns', value: 'Unlimited' },
        { label: 'Dashboard analytics', value: 'Custom' },
        { label: 'Support SLA', value: '4 hrs (Dedicated account manager)' },
      ],
    },
  ],
} as const;

