import '../loadDotenv.js';
import 'reflect-metadata';
import { DataSource } from 'typeorm';
import { loadEnv } from './env.js';
import {
  AnalyticsEvent,
  AuditLog,
  Branch,
  BusinessCategory,
  Campaign,
  CampaignSend,
  CardMessage,
  CmsBanner,
  CmsPage,
  Customer,
  CustomerCardEnrolment,
  CustomerNotificationPreference,
  CustomerSavedLocation,
  FeatureFlag,
  IdempotencyRecord,
  Invoice,
  LoyaltyCard,
  LoyaltyCardReward,
  Merchant,
  MerchantBranchPhoto,
  MerchantKycDocument,
  MerchantOnboardingApplication,
  MerchantPushQuota,
  MerchantSubscription,
  MerchantUser,
  OfferRedemption,
  OfferRedemptionSession,
  OtpChallenge,
  Payment,
  PlatformPermission,
  PlatformRole,
  PlatformRolePermission,
  PlatformStaff,
  PlatformStaffRole,
  ReferralEvent,
  RefreshToken,
  RewardRedemption,
  SpecialOffer,
  SpecialOfferBranchScope,
  SpecialOfferTargetCustomer,
  StampEvent,
  SubscriptionPlan,
  SupportTicket,
  SupportTicketMessage,
} from '../entities/index.js';

const env = loadEnv();

const logging =
  process.env.NODE_ENV === 'development' && process.env.TYPEORM_LOGGING === 'true';

const AppDataSource = new DataSource({
  type: 'postgres',
  url: env.DATABASE_URL,
  entities: [
    AnalyticsEvent,
    AuditLog,
    Branch,
    BusinessCategory,
    Campaign,
    CampaignSend,
    CardMessage,
    CmsBanner,
    CmsPage,
    Customer,
    CustomerCardEnrolment,
    CustomerNotificationPreference,
    CustomerSavedLocation,
    FeatureFlag,
    IdempotencyRecord,
    Invoice,
    LoyaltyCard,
    LoyaltyCardReward,
    Merchant,
    MerchantBranchPhoto,
    MerchantKycDocument,
    MerchantOnboardingApplication,
    MerchantPushQuota,
    MerchantSubscription,
    MerchantUser,
    OfferRedemption,
    OfferRedemptionSession,
    OtpChallenge,
    Payment,
    PlatformPermission,
    PlatformRole,
    PlatformRolePermission,
    PlatformStaff,
    PlatformStaffRole,
    ReferralEvent,
    RefreshToken,
    RewardRedemption,
    SpecialOffer,
    SpecialOfferBranchScope,
    SpecialOfferTargetCustomer,
    StampEvent,
    SubscriptionPlan,
    SupportTicket,
    SupportTicketMessage,
  ],
  migrations: [__dirname + '/../migrations/*.js'],
  synchronize: process.env.DB_SYNC === 'true',
  logging,
});

export { AppDataSource };
export default AppDataSource;
